In [ ]:
#How to read files
#Reading CSV:-
df = pd.read_csv("sales.csv")

#Reading Excel:-
df = pd.read_Excel("sales.xls")

#Reading JSON:-
df = pd.read_JSON("sales.json")

In [ ]:
#Missing Values--- isna,isnull
#counting missing values -- isna.sum, isnull.sum
#deleting Missing values -- dropna,
#replace or fillna
NAN--- NOT A NUMBER(null values)

In [ ]:
#Cleaning the Data:-
import pandas as pd
df = pd.Series(
    [5000,7000,None,9000,8000,10000,None],
    index=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])
print(df)

Monday        5000.0
Tuesday       7000.0
Wednesday        NaN
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           NaN
dtype: float64

In [ ]:
df.isna()
df.isna().sum
df.dropna()

Monday       5000.0
Tuesday      7000.0
Thursday     9000.0
Friday       8000.0
Saturday    10000.0
dtype: float64

In [ ]:
df.fillna(0)

Monday        5000.0
Tuesday       7000.0
Wednesday        0.0
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday           0.0
dtype: float64

In [ ]:
df.fillna("no data")

Monday        5000.0
Tuesday       7000.0
Wednesday    no data
Thursday      9000.0
Friday        8000.0
Saturday     10000.0
Sunday       no data
dtype: object

In [ ]:
import pandas as pd
employees = {
    "EmpID": [101,102,103,104],
    "Name": ["Asha",None,"Meena","Sai"],
    "Department": ["Sales","IT","HR",None],
    "Salary": [45000,6000,None,89000]
}
I =[901,902,903,904]
df_emp = pd.DataFrame(employees,index = I)
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT   6000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp.isnull()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp.fillna({
    'Name': 'Unkown',
    'Salary': 0,
    'Department': 0
})
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT   6000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT   6000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp['Salary'].fillna(df['Salary'].max())

901    45000.0
902     6000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df['Salary'].min())

901    45000.0
902     6000.0
903        0.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df['Salary'].std())

901    45000.000000
902     6000.000000
903    41158.231255
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df['Salary'].var())

901    4.500000e+04
902    6.000000e+03
903    1.694000e+09
904    8.900000e+04
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df['Salary'].mean())

901    45000.0
902     6000.0
903    35000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
import pandas as pd
employees = {
    "EmpID": [101,102,103,104],
    "Name": ["Asha",None,"Meena","Sai"],
    "Department": ["Sales","IT","HR",None],
    "Salary": [45000,6000,None,89000]
}
I =[901,902,903,904]
df = pd.DataFrame(employees,index = I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT   6000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df.head(2)

     EmpID  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT   6000.0

In [ ]:
df.tail(2)

     EmpID   Name Department   Salary
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df['EmpID'] = 103
print(df)

     EmpID   Name Department   Salary
901    103   Asha      Sales  45000.0
902    103   None         IT   6000.0
903    103  Meena         HR      NaN
904    103    Sai       None  89000.0

In [ ]:
df[['Name','Salary']]

      Name   Salary
901   Asha  45000.0
902   None   6000.0
903  Meena      NaN
904    Sai  89000.0

In [ ]:
df[df["Salary"]>50000]

     EmpID Name Department   Salary
904    103  Sai       None  89000.0

In [ ]:
df["Salary"]>500000

901    False
902    False
903    False
904    False
Name: Salary, dtype: bool

In [ ]:
print(df['Department'] == 'IT')

901    False
902     True
903    False
904    False
Name: Department, dtype: bool

In [ ]:
df[df["EmpID"] == 103]

     EmpID   Name Department   Salary
901    103   Asha      Sales  45000.0
902    103   None         IT   6000.0
903    103  Meena         HR      NaN
904    103    Sai       None  89000.0